# This file generates the GitHub Actions matrix.

---
include:
  - board: seeeduino_xiao_ble
    shield: sparkleKeyboard2_left rgbled_adapter

  - board: seeeduino_xiao_ble
    shield: sparkleKeyboard2_right rgbled_adapter
